### ISSUE TITLE
Merge with BeltSorter mod?

### ISSUE THREAD

**Issue by judos** [Hermios/Factorio#1]
Hi Hermios,

I just saw your change of the BeltSorter mod. I recently added an advanced beltSorter which also let's you choose on which lane to distribute items (A bit differently of course than how you did).
If you like we could work together on the beltSorter mod and also update the basic beltSorter. My idea would be:
- It requires some research to enable the checkbox option
- When research is done it let's you select the same you implemented

Or another idea could be to provide a "mode of operation" which you can choose some option. E.g. "left lane first", "distribute evenly", "right lane first".

Cheers,
judos

**Comment by Hermios** [comment]
Hi JudosHey, cool, thanks for the answer.Well, I am not sure that you had the last version of my mod. And the description doesn't match!So my first suggestion would be... that I update the description :D
More seriously, I think that the current version is complete enough, for the lane, as it allows you to filter per lane.We can add other options to choose, but I think that it would be a little bit too much.However, I noticed that there is a problem with the speed : even when the entering belt is full, items are dispatched less regularly on the outgoing one. It is not so great for the production. I think that would be a real challenge to maintain the same flow for the ongoing and outgoing belts. Besides, someone asked me to adapt it to belts from Bob's mod.Another enhancement : The filter! It is really not usable right now
For information, I imported my mod under the name "Line-sorter", as I wanted to share it, but I couldn't take the same name as you.I invite you to test it, and tell me what you think. If you like it, I'll give you the code with belt-sorter names instead of line-sorter, so you can directly integrate to yours (If it is still relevant, I didn't test your update).Anyway, many thanks for your mode, it helped me a lot for doing what I did, and actually, I still use your code (That I find it really efficient) to develop other stuffs. So thanks for that too.
 Mit freundlichen Grüßen / Best Regards / Cordialement
Hermios  

   

 Le Lundi 17 octobre 2016 15h58, judos <notifications@github.com> a écrit :
 

 Hi Hermios,I just saw your change of the BeltSorter mod. I recently added an advanced beltSorter which also let's you choose on which lane to distribute items (A bit differently of course than how you did).
If you like we could work together on the beltSorter mod and also update the basic beltSorter. My idea would be:   
   - It requires some research to enable the checkbox option
   - When research is done it let's you select the same you implemented
Or another idea could be to provide a "mode of operation" which you can choose some option. E.g. "left lane first", "distribute evenly", "right lane first".Cheers,
judos—
